# Generated by Django 4.2.6 on 2024-10-27 20:05

import apps.images.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.images.models.generate_image_filename)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(choices=[('org_photo', 'Organisation Photo'), ('org_logo', 'Organisation Logo'), ('doctor_avatar', 'Doctor Avatar'), ('user_avatar', 'User Avatar')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='doctors.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
