# Generated by Django 5.0.4 on 2024-05-02 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("images", "0001_initial"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orglogo",
            name="org_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_logo",
                to="organisations.organisation",
            ),
        ),
        migrations.AddField(
            model_name="orgphoto",
            name="org_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="organisations.organisation",
            ),
        ),
    ]
