version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "3003:3003"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:3003"
    env_file:
      - .env.dev
#    environment:
#      - DB_HOST=db
#      - DB_NAME=mydb-dev
#      - DB_USER=vinhle
#      - DB_PASS=password
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - volume:/var/lib/postgresql/data

volumes:
  volume: