version: '3'

services:
  db:
    image: postgres:15
    volumes:
      - pg_data_vol:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bob
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=amedice_dev
    ports:
      - "5432:5432"

volumes:
  pg_data_vol: