# Generated by Django 4.2.6 on 2024-02-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgcategory",
            name="page_content",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
