# Generated by Django 4.2.6 on 2023-11-16 22:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Больница", "Hospital"),
                            ("Клиника", "Clinic"),
                            ("Лаборатория", "Laboratory"),
                            ("Стоматология", "Dental Clinic"),
                            ("Аптека", "Pharmacy"),
                            ("Медицинский центр", "Medical Center"),
                            ("Оптика", "Optics"),
                            ("Санаторий", "Sanatorium"),
                            ("Медицинское учебное заведение", "Medical School"),
                            ("Медицинское оборудование", "Medical Equipment"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        default="This is a default description of medical institution",
                        max_length=1000,
                    ),
                ),
                (
                    "services",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("Хирургия", "Surgery"),
                                ("Терапия", "Therapy"),
                                ("Педиатрия", "Pediatrics"),
                                ("Стоматология", "Dentistry"),
                                ("Неврология", "Neurology"),
                                ("Психиатрия", "Psychiatry"),
                                ("Офтальмология", "Ophthalmology"),
                                ("Рентген", "Xray"),
                                ("УЗИ", "Ultrasound"),
                                ("МРТ", "Mri"),
                                ("КТ", "Ct"),
                                ("Лаборатория", "Laboratory"),
                                ("Физиотерапия", "Physiotherapy"),
                                ("Массаж", "Massage"),
                                ("Косметология", "Cosmetology"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "doctors_speciality",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("Хирург", "Surgeon"),
                                ("Терапевт", "Therapist"),
                                ("Педиатр", "Pediatrician"),
                                ("Дантист", "Dentist"),
                                ("Невролог", "Neurologist"),
                                ("Психиатр", "Psychiatrist"),
                                ("Офтальмолог", "Ophthalmologist"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone_number", models.CharField(max_length=100)),
                (
                    "doctors",
                    models.ManyToManyField(blank=True, null=True, to="doctors.doctor"),
                ),
            ],
        ),
    ]
