# Generated by Django 4.2.6 on 2023-11-27 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organisations", "0001_initial"),
        ("reviews", "0001_initial"),
        ("doctors", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgownerslink",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="doctors_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.doctor",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="org_admins",
            field=models.ManyToManyField(
                blank=True, related_name="org_admins", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="org_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="org_reviews",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_reviews",
                to="reviews.review",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="org_socials",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_socials",
                to="organisations.orgsocials",
            ),
        ),
        migrations.AddField(
            model_name="orgadminslink",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.organisation",
            ),
        ),
        migrations.AddField(
            model_name="orgadminslink",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
