# Generated by Django 4.2.6 on 2023-11-23 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="org_reviews",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_reviews",
                to="reviews.review",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="org_socials",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_socials",
                to="organisations.orgsocials",
            ),
        ),
    ]
