# Generated by Django 4.2.6 on 2024-01-31 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_delete_userreviewlink"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("socials", "0001_initial"),
        ("organisations", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReviewLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reviews.review"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="organisation",
            name="org_socials",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="org_socials",
                to="socials.orgsocials",
            ),
        ),
        migrations.DeleteModel(
            name="OrgSocials",
        ),
    ]
