# Generated by Django 4.2.6 on 2023-12-13 21:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="org_category",
            field=models.CharField(
                choices=[
                    ("Медицинский центр", "Med Center"),
                    ("Лаборатория", "Laboratory"),
                    ("Стоматология", "Dental Clinic"),
                    ("Диагностический центр", "Diagnostic Center"),
                    ("Офтальмологическая клиника", "Eye Clinic"),
                    ("Детская клиника", "Kids Clinic"),
                    ("Косметологический центр", "Cosmetology Center"),
                    ("Больница", "Gos Hospital"),
                    ("Амбулатория", "Gos Ambulatory"),
                    ("Детская больница", "Gos Kids Hospital"),
                    ("Поликлиника", "Gos Polyclinic"),
                    ("Стоматологическая поликлиника", "Gos Dental Polyclinic"),
                    ("Роддом", "Gos Maternity Hospital"),
                    ("Диспансер", "Gos Dispensary"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="org_directions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Урология", "Urology"),
                        ("Терапия", "Therapy"),
                        ("Стоматология", "Dentistry"),
                        ("Дерматология", "Dermatology"),
                        ("Неврология", "Neurology"),
                        ("Косметология", "Cosmetology"),
                        ("Венерология", "Venereology"),
                        ("Ортопедия", "Ortopedics"),
                        ("Физиотерапия", "Physiotherapy"),
                        ("Хирургия", "Surgery"),
                        ("Эндокринология", "Endocrinology"),
                        ("Онкология", "Oncology"),
                        ("Педиатрия", "Pediatrics"),
                        ("Кардиология", "Cardiology"),
                        ("Отоларингология", "Oto Rhino Laryngology"),
                        ("Психиатрия", "Psychiatry"),
                        ("Офтальмология", "Ophthalmology"),
                        ("Гинекология", "Gynecology"),
                    ],
                    max_length=40,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="org_id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="org_main_phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
