# Generated by Django 4.2.6 on 2023-12-14 21:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_initial"),
        ("doctors", "0002_initial"),
        ("organisations", "0003_alter_organisation_org_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgCategory",
            fields=[
                (
                    "category_id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True, db_index=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        db_index=True,
                        max_length=40,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="organisation",
            name="doctors_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctors.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="org_directions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("urology", "Urology"),
                        ("therapy", "Therapy"),
                        ("dentistry", "Dentistry"),
                        ("dermatology", "Dermatology"),
                        ("neurology", "Neurology"),
                        ("cosmetology", "Cosmetology"),
                        ("venereology", "Venereology"),
                        ("ortopedics", "Ortopedics"),
                        ("physiotherapy", "Physiotherapy"),
                        ("surgery", "Surgery"),
                        ("endocrinology", "Endocrinology"),
                        ("oncology", "Oncology"),
                        ("pediatrics", "Pediatrics"),
                        ("cardiology", "Cardiology"),
                        ("oto_rhino_laryngology", "Oto Rhino Laryngology"),
                        ("psychiatry", "Psychiatry"),
                        ("ophthalmology", "Ophthalmology"),
                        ("gynecology", "Gynecology"),
                    ],
                    max_length=40,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="org_reviews",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="org_reviews",
                to="reviews.review",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="org_socials",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="org_socials",
                to="organisations.orgsocials",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="org_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="organisations.orgcategory",
            ),
        ),
    ]
