# Generated by Django 4.2.6 on 2024-01-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organisations",
            "0003_userreviewlink_alter_organisation_org_socials_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="org_working_hours",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
