# Generated by Django 4.2.6 on 2023-12-15 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0004_orgcategory_alter_organisation_doctors_list_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgDirection",
            fields=[
                (
                    "direction_id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True, db_index=True)),
            ],
        ),
        migrations.AlterField(
            model_name="organisation",
            name="org_category",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organisations.orgcategory",
            ),
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="org_directions",
        ),
        migrations.AddField(
            model_name="organisation",
            name="org_directions",
            field=models.ManyToManyField(blank=True, to="organisations.orgdirection"),
        ),
    ]
