# Generated by Django 4.2.6 on 2024-02-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_delete_userreviewlink"),
        ("organisations", "0005_alter_organisation_org_socials"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisation",
            name="org_reviews",
        ),
        migrations.AddField(
            model_name="organisation",
            name="org_reviews",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="org_reviews", to="reviews.review"
            ),
        ),
    ]
