# Generated by Django 4.2.6 on 2024-02-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_delete_userreviewlink"),
        ("organisations", "0006_remove_organisation_org_reviews_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="org_reviews",
            field=models.ManyToManyField(
                blank=True, related_name="org_reviews", to="reviews.review"
            ),
        ),
    ]
