# Generated by Django 4.2.6 on 2024-01-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrgSocials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whatsapp", models.CharField(max_length=100)),
                ("viber", models.CharField(max_length=100)),
                ("telegram", models.CharField(max_length=100)),
                ("instagram", models.CharField(max_length=100)),
                ("facebook", models.CharField(max_length=100)),
                ("vkontakte", models.CharField(max_length=100)),
                ("odnoklassniki", models.CharField(max_length=100)),
                ("imo", models.CharField(max_length=100)),
                ("youtube", models.CharField(max_length=100)),
            ],
        ),
    ]
