# Generated by Django 4.2.6 on 2024-01-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("socials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgsocials",
            name="facebook",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orgsocials",
            name="imo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orgsocials",
            name="instagram",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orgsocials",
            name="odnoklassniki",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orgsocials",
            name="telegram",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orgsocials",
            name="viber",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orgsocials",
            name="vkontakte",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orgsocials",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orgsocials",
            name="youtube",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
