# Generated by Django 4.2.6 on 2024-01-31 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserReviewLink",
        ),
    ]
