# Generated by Django 4.2.6 on 2023-11-16 22:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "speciality",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("Хирург", "Surgeon"),
                                ("Терапевт", "Therapist"),
                                ("Педиатр", "Pediatrician"),
                                ("Дантист", "Dentist"),
                                ("Невролог", "Neurologist"),
                                ("Психиатр", "Psychiatrist"),
                                ("Офтальмолог", "Ophthalmologist"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("phone_number", models.CharField(max_length=100)),
            ],
        ),
    ]
