# Generated by Django 5.0.4 on 2024-05-02 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="organisationreview",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reviews.review"
            ),
        ),
        migrations.AddField(
            model_name="doctorreview",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reviews.review"
            ),
        ),
    ]
